[providers.age]
type = "age"
recipients = ["age1myar7u3lv655j90ze2yqlgl5a4n3l6t4wc0xy0tdtgzeqvjghelq42wuns"]

[secrets]
ZAI_API_KEY= { provider = "age", value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGUDhicVo5ZkN0MllTZVNsODdTSDl1M2NBQ1dWMjRVU1ZMRnN4VWRqd1QwClNoNGdpR0licVZSRWZCSmdaWWNHMzRqQkJ1Yk0xMHFRT3VURkhZT0dWaGMKLT4gMEI0MTpRVEEtZ3JlYXNlICUjeThcIwpZd2cwTFNwdW9JbExRNW5rU2RvaEhqNGJTZmVyT282QWlRd01Fd05YcDVuODRUanU4WUVpcGtiOElUT0NqNk1GCm5qVWdqcFljRFQ5T1pIUXdCclVyMXZZVmV4RThFME0yK3g5MjZBWHNWZ3BBU1ZQTUVqL3gKLS0tIHpSZGVFYTVsOVhEL1YxY2F0SG5HNU1XWnl3OG5Va3ZpYnVhQ1hDK2gxMlUKB5txzOZtF6uAvcaZ5b7M4jCpbhfKZR3p0dtkqVpUUiOEIOwoB9OLJp7soL1DUsm/v8/ky/ZDBBC+hVAkVmJRoiDTzlsHS7fREOEbj+Us6YfG" }
